input_dir: ../../Riot/
output_dir: ../../Riot/Generated/
ib:  
  inputs:
    - ../Tools/Templates/buildable/
    - Modules/
  filter: ^((?!(DeactivateAccountViewController|Security)).)*\.(storyboard)
  outputs:
    templateName: scenes-swift4
    output: Storyboards.swift
strings:
  - inputs: Assets/en.lproj/Vector.strings
    outputs:
      templatePath: Templates/Strings/flat-swift4-vector.stencil
      output: Strings.swift
      params:
        className: VectorL10n
        publicAccess: true
  - inputs: Modules/MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
    outputs:
      templatePath: Templates/Strings/matrixkit-flat-swift4-vector.stencil
      output: MatrixKitStrings.swift
      params:
        className: MatrixKitL10n
        publicAccess: true
xcassets:  
  inputs:
    - Assets/Images.xcassets
    - Assets/SharedImages.xcassets
  outputs:
    templateName: swift4
    output: Images.swift
plist:
  inputs: Assets/Riot-Defaults.plist
  outputs:
    templateName: runtime-swift4
    output: RiotDefaults.swift
    params:
      enumName: RiotDefaults
